
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: localhost

development:
  <<: *default
  database: table_football_development

test:
  <<: *default
  database: table_football_test

production:
  <<: *default
  database: table_football_production
  username: table_football
  password: <%= ENV['TABLE_FOOTBALL_DATABASE_PASSWORD'] %>
