# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15163f0985325143f0aad7df60393619d994306f5caa3b070b9a842984870fe3a774db16051af4809e7bc8dff0c99c547672d154cb1a7771cda5e6e51fb79eda

test:
  secret_key_base: dc9a8cd749f58459e5c91b525772ed8275fde4d2614d5222e3cc14cdf630d0c0591221535c07babfecf03c11248a26a5e05829591106c48dfec2565a4fdea407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
